config/routes.rb
Rails.application.routes.draw do
  resources :departaments
  resources :products, only: [:new, :create, :destroy, :edit, :update]
  get "/products/search" => "products#search", as: :search_product
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/departament.rb
class Departament < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :departament

  validates :name, length: { minimum: 5 }, presence: true
  validates :price, presence: true
  validates :quantitiy, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departaments_controller.rb
class DepartamentsController < ApplicationController
  before_action :set_departament, only: %i[ show edit update destroy ]

  # GET /departaments or /departaments.json
  def index
    @departaments = Departament.all
  end

  # GET /departaments/1 or /departaments/1.json
  def show
  end

  # GET /departaments/new
  def new
    @departament = Departament.new
  end

  # GET /departaments/1/edit
  def edit
  end

  # POST /departaments or /departaments.json
  def create
    @departament = Departament.new(departament_params)

    respond_to do |format|
      if @departament.save
        format.html { redirect_to departament_url(@departament), notice: "Departament was successfully created." }
        format.json { render :show, status: :created, location: @departament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departaments/1 or /departaments/1.json
  def update
    respond_to do |format|
      if @departament.update(departament_params)
        format.html { redirect_to departament_url(@departament), notice: "Departament was successfully updated." }
        format.json { render :show, status: :ok, location: @departament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departaments/1 or /departaments/1.json
  def destroy
    @departament.destroy

    respond_to do |format|
      format.html { redirect_to departaments_url, notice: "Departament was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departament
      @departament = Departament.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departament_params
      params.require(:departament).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:edit, :update, :destroy]
  def index
    @products_list_order_name = Product.order(:name).limit 5
    @products_list_order_price = Product.order(:price).limit 2
  end

  def new
    @product = Product.new
    renderiza :new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:notice] = "Produto adicionado com sucesso!"
      redirect_to root_url
    else
      renderiza :new
    end
  end

  def edit
    renderiza :edit
  end

  def update
    if @product.update product_params
      flash[:notice] = "Produto atualizado com sucesso!"
      redirect_to root_url
    else
      renderiza :edit
    end
  end

  def search
    @name_to_search = params[:name]
    @result = Product.where "name like ?", "%#{@name_to_search}%"
  end
  def destroy
    @product.destroy
    redirect_to root_url
  end


  private
  def renderiza(view)
    @departaments = Departament.all
    render view
  end

  def set_product
    id = params[:id]
    @product = Product.find(id)
  end

  def product_params
    params.require(:product).permit :name, :description, :quantitiy, :price, :departament_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departaments_helper.rb
module DepartamentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/departaments/_departament.html.erb
<div id="<%= dom_id departament %>">
  <p>
    <strong>Name:</strong>
    <%= departament.name %>
  </p>

</div>

app/views/departaments/_form.html.erb
<%= form_with(model: departament) do |form| %>
  <% if departament.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departament.errors.count, "error") %> prohibited this departament from being saved:</h2>

      <ul>
        <% departament.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departaments/edit.html.erb
<h1>Editing departament</h1>

<%= render "new", departament: @departament %>

<br>

<div>
  <%= link_to "Show this departament", @departament %> |
  <%= link_to "Back to departaments", departaments_path %>
</div>

app/views/departaments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departaments</h1>

<div id="departaments">
  <% @departaments.each do |departament| %>
    <%= render departament %>
    <p>
      <%= link_to "Show this departament", departament %>
    </p>
  <% end %>
</div>

<%= link_to "New departament", new_departament_path %>

app/views/departaments/new.html.erb
<h1>New departament</h1>

<%= render "new", departament: @departament %>

<br>

<div>
  <%= link_to "Back to departaments", departaments_path %>
</div>

app/views/departaments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @departament %>

<div>
  <%= link_to "Edit this departament", edit_departament_path(@departament) %> |
  <%= link_to "Back to departaments", departaments_path %>

  <%= button_to "Destroy this departament", @departament, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>t-Shirt Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
  <%= nav_bar brand: "Fawacom", brand_link: root_url do %>

    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item"><%= link_to "Novo Produto", new_product_path, class: "nav-item" %></li>
          <li class="nav-item"><%= link_to "Departamentos", departaments_path, class: "nav-item" %></li>
        </ul>
        <%= form_tag search_product_path, method: :get, class: "navbar-new navbar-right" do %>
          <div class="form-group">
            <%= text_field_tag :name, @name_to_search, class: "new-control" %>
            <%= button_to "Search", nil, class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/products/_form.erb
<% @product.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
<% end %>

<%= form_for @product do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: ["new-control", "new-control-lg"] %>
  </div>

  <div class="form-group">
    <%= f.label :departament %>
    <%= f.collection_select :departament_id, @departaments, :id, :name, {}, class: ["new-control", "new-control-lg"] %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: ["new-control", "new-control-lg"], rows: 4 %>
  </div>

  <div class="form-inline">
    <div class="form-group">
      <%= f.label :quantitiy %>
      <%= f.number_field :quantitiy, step: 1, class: ["new-control", "new-control-lg"]  %>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, step: 0.1, class: ["new-control", "new-control-lg"]  %>
    </div>
    <%= f.submit name_of_button, class: ["btn", "btn-primary"] %>
  </div>

<% end %>

app/views/products/_product.erb
<tr>
  <td><%=  product.id %></td>
  <td><%=  product.name %></td>
  <td><%=  product.description%></td>
  <td class="text-right">R$ <%=  product.price %></td>
  <td class="text-center"><%=  product.quantitiy %></td>
  <td class="text-center">
    <%= button_to "Remover", product,
                  method: :delete,
                  class: "btn btn-danger",
                  data: { confirm: "Tem certeza que deseja remover o produto?" } %>

  </td>
  <td class="text-center">
    <%= link_to "Edit", edit_product_path(product), class: "btn btn-warning" %>
  </td>
</tr>

app/views/products/edit.erb
<%= render partial: 'form', locals: { name_of_button: "Update Product" } %>

app/views/products/index.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th class="text-center">#</th>
    <th>Nome</th>
    <th>Descrição</th>
    <th class="text-center">Preço</th>
    <th class="text-center">Quantidade</th>
    <th class="text-center">Remove</th>
    <th class="text-center">Edit</th>
  </tr>
  </thead>
  <tbody>
  <%= render partial: "product", collection: @products_list_order_name %>
  </tbody>
</table>

<hr />

<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Preço</th>
    <th>Quantidade</th>
  </tr>
  </thead>
  <tbody>
  <%= render partial: "product", collection: @products_list_order_price %>
  </tbody>
</table>

app/views/products/new.erb
<%= render partial: 'form', locals: { name_of_button: "Create Product" } %>

app/views/products/search.erb
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th class="text-center">#</th>
    <th>Nome</th>
    <th>Descrição</th>
    <th class="text-center">Preço</th>
    <th class="text-center">Quantidade</th>
    <th class="text-center">#</th>
  </tr>
  </thead>
  <tbody>
  <%= render partial: "product", collection: @name_to_search %>
  </tbody>
</table>